version: '3.9'
services:
  node:
    build:
      context: ./
    ports:
      - '3333:3333'
      - '8080:8080'
    container_name: job_bank_api
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/app
    #  - /usr/src/app/node_modules
    user: node
    command:
      - yarn
      - dev

  mysql:
    container_name: job_bank_db
    image: 'mysql/mysql-server:8.0'
    volumes:
      - mysql_volume:/var/lib/mysql/data
      - ./dockerConfig/mysql-dev-init.sql:/docker-entrypoint-initdb.d/init.sql # will setup dev database adonis_app for us
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  redis:
    container_name: job_bank_redis
    image: redis:alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

volumes:
  mysql_volume:
  redis_volume:
